### PR TITLE
[Homework #18] - React UI by Antonina Vechorko

### PR DESCRIPTION
**Pull request by antoninavechorko**
@ilya-ischenko pls check this hw, thank you.

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
Does this react app work for you?

**Comment by antoninavechorko** [comment]
Screenshot 2023-10-17 at 16 09 23
Screenshot 2023-10-17 at 16 09 33

**Comment by antoninavechorko** [comment]
@ilya-ischenko yes, it is working. It seems that public folder was in .gitignore, add it as well. Hope it will be working now.

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
