### PR TITLE
[Homework #13] - Enviroments and preprocessors by Oleksii Achkevych

### PR DESCRIPTION
**Pull request by ste1nerr**

### CODE REVIEW

**Comment by ste1nerr** [comment]
need to re-work it

**Comment by ste1nerr** [comment]
i have a question, when I write npm run build it updates the styles and it shows them when I change them in the browser tab, but when I make changes with the server running (npm start) and save the file they are not shown in the browser tab for some reason.

**Comment by ilya-ischenko** [comment]
> i have a question, when I write npm run build it updates the styles and it shows them when I change them in the browser tab, but when I make changes with the server running (npm start) and save the file they are not shown in the browser tab for some reason.

I did not quite catch it.
You change styles in browser?

**Comment by ste1nerr** [comment]
> > i have a question, when I write npm run build it updates the styles and it shows them when I change them in the browser tab, but when I make changes with the server running (npm start) and save the file they are not shown in the browser tab for some reason.
> 
> I did not quite catch it. You change styles in browser tab?

I have the following task:
A project with 2 scripts: npm run build and npm start
npm run build builds compressed CSS
npm start monitors scss or stylus files
1. npm run build I did 
2. npm start only tracks changes, but when I press ctrl + s they do not immediately appear on the page, I need to write the command npm run build and then they will appear on the page
is this how it should be?

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
