### PR TITLE
[Homework #3] - HTML by Usmonbek Rustamov

### PR DESCRIPTION
**Pull request by usmonbek-umarbekovich**
Hey,

I completed homework for HTML,
Thanks for your time in advance

### CODE REVIEW

**Review by VitalikMelnyk — COMMENTED** [review]
Everything looks good!
Just one note:
Please, create an appropriate folder for `images` and `files` inside the `assets` folder.

**Comment by VitalikMelnyk** [comment]
Well Done @usmonbek-umarbekovich!
Approved.

**Comment by usmonbek-umarbekovich** [comment]
Do I need to delete this branch now?

**Comment by VitalikMelnyk** [comment]
No, you needn't delete it.

**Pull request merged**
