### PR TITLE
[Homework #15] - Typescript by Antonina Vechorko

### PR DESCRIPTION
**Pull request by antoninavechorko**
@solvd-mmelnyk kindly review this homework, thank you

### CODE REVIEW

**Review by solvd-mmelnyk — APPROVED** [review]
Great work!

**Review by solvd-mmelnyk — CHANGES_REQUESTED** [review]
please do not modify main package.json file
you can create local one if you need
it is not good tone to change general one only for your homework!

**Comment by antoninavechorko** [comment]
yes, sure
did it by mistake, sorry for this

**Comment by antoninavechorko** [comment]
returned files to conditions as they are in main branch

**Comment by solvd-mmelnyk** [comment]
> returned files to conditions as they are in main branch

@antoninavechorko please also do not change yarn.lock file

**Comment by antoninavechorko** [comment]
@solvd-mmelnyk i returned yarn file, package.json. and package-log.json to the condition as they are in main branch. Is there any issues still?

**Comment by antoninavechorko** [comment]
@solvd-mmelnyk these changes were affected by first commit in this branch as i see from my commit history, so I will better create new PR. Thank you!

**Pull request closed without merging**
