### PR TITLE
[Homework #11] - JS-DOM by Max Hirning

### PR DESCRIPTION
**Pull request by Max-Hirning**

### CODE REVIEW

**Review by ilya-ischenko — COMMENTED** [review]
One of the requirements -` Click handler should be implemented using Event Delegation approach`

https://javascript.info/event-delegation

**Comment by Max-Hirning** [comment]
Fixed.
Rewrote event listener(added it to tbody)

**Review by ilya-ischenko — COMMENTED** [review]
1. Smth wrong with cell numbers, it does not make 
Screenshot 2023-08-21 at 10 30 39
Screenshot 2023-08-21 at 10 30 36
sense for me

2. Some cells becomes bigger when you click on them, it cause layout changes which does not look good
Screenshot 2023-08-21 at 10 32 46
Screenshot 2023-08-21 at 10 31 35
Screenshot 2023-08-21 at 10 31 28

**Comment by Max-Hirning** [comment]
Fixed

**Review by ilya-ischenko — APPROVED** [review]
Well done!
Approved.

**Pull request merged**
